INSERT INTO yedek_parcalar (yedek_id, model_id, parca_adi, aciklama, fiyat, stok_id) VALUES
(1, 1, 'Sağ Ön Çamurluk Sinyali', 'Sağ ön çamurluk üzerinde yer alan, aracın sağa dönüş veya şerit değiştirme sinyalini ileten sinyal lambasıdır. Görünürlüğü artırır ve trafikte güvenliği sağlar.', 26.15, 1),
(2, 1, 'Sağ Arka Çamurluk Sinyali', 'Sağ arka çamurlukta bulunan, aracın sağa dönüş veya şerit değiştirme sinyalini gösteren lambadır. Takip eden araçlara yön bildirimi yaparak sürüş güvenliğini artırır.', 35.58, 2),
(3, 1, 'Sol Ön Çamurluk Sinyali', 'Sol ön çamurlukta yer alan, aracın sola dönüş veya şerit değiştirme sinyalini gösteren lambadır. Görünürlüğü artırarak trafikte güvenliği sağlar.', 45.46, 3),
(4, 1, 'Sol Arka Çamurluk Sinyali', 'Sol arka çamurlukta bulunan sinyal lambasıdır. Aracın sola dönüş veya şerit değiştirme sırasında yön bildirmesini sağlar ve sürüş güvenliğini artırır.', 47.24, 4),
(5, 1, 'Sağ Sis Farı', 'Ön tamponun sağ tarafında bulunan sis farıdır. Yoğun sis, yağmur veya kar gibi düşük görüş koşullarında yolun daha net görülmesini sağlar.', 47.24, 5),
(6, 1, 'Fren Hortumu', 'Fren sisteminde, fren hidroliğini tekerleklere ileten esnek bağlantı parçasıdır. Frenleme sırasında basınç iletimini sağlar ve güvenli duruş için kritik öneme sahiptir.', 50.39, 6),
(7, 1, 'Krank Keçesi AFT', 'Motorun krank milinde bulunan keçedir. Yağ sızıntısını önler ve motorun verimli çalışmasına yardımcı olur.', 50.67, 7),
(8, 1, 'Krank Keçesi BGA', 'Motorun krank milinde bulunan keçedir. Yağ sızıntısını önler ve motorun verimli çalışmasına yardımcı olur.', 62.36, 8),
(9, 1, 'Krank Keçesi BFI', 'Motorun krank milinde bulunan keçedir. Yağ sızıntısını önler ve motorun verimli çalışmasına yardımcı olur.', 65.78, 9),
(10, 1, 'Krank Keçesi IAT', 'Motorun krank milinde bulunan keçedir. Yağ sızıntısını önler ve motorun verimli çalışmasına yardımcı olur.', 63.24, 10),
(11, 1, 'Sağ Ön Çamurluk Sinyali', 'Sağ ön çamurluk üzerinde yer alan, aracın sağa dönüş veya şerit değiştirme sinyalini ileten sinyal lambasıdır. Görünürlüğü artırır ve trafikte güvenliği sağlar.', 26.15, 11),
(12, 1, 'Sağ Arka Çamurluk Sinyali', 'Sağ arka çamurlukta bulunan, aracın sağa dönüş veya şerit değiştirme sinyalini gösteren lambadır. Takip eden araçlara yön bildirimi yaparak sürüş güvenliğini artırır.', 35.58, 12),
(13, 1, 'Sol Ön Çamurluk Sinyali', 'Sol ön çamurlukta yer alan, aracın sola dönüş veya şerit değiştirme sinyalini gösteren lambadır. Görünürlüğü artırarak trafikte güvenliği sağlar.', 45.46, 13),
(14, 1, 'Sol Arka Çamurluk Sinyali', 'Sol arka çamurlukta bulunan sinyal lambasıdır. Aracın sola dönüş veya şerit değiştirme sırasında yön bildirmesini sağlar ve sürüş güvenliğini artırır.', 47.24, 14),
(15, 1, 'Sağ Sis Farı', 'Ön tamponun sağ tarafında bulunan sis farıdır. Yoğun sis, yağmur veya kar gibi düşük görüş koşullarında yolun daha net görülmesini sağlar.', 47.24, 15),
(16, 1, 'Fren Hortumu', 'Fren sisteminde, fren hidroliğini tekerleklere ileten esnek bağlantı parçasıdır. Frenleme sırasında basınç iletimini sağlar ve güvenli duruş için kritik öneme sahiptir.', 50.39, 16),
(17, 1, 'Krank Keçesi AFT', 'Motorun krank milinde bulunan keçedir. Yağ sızıntısını önler ve motorun verimli çalışmasına yardımcı olur.', 50.67, 17),
(18, 1, 'Krank Keçesi BGA', 'Motorun krank milinde bulunan keçedir. Yağ sızıntısını önler ve motorun verimli çalışmasına yardımcı olur.', 62.36, 18),
(19, 1, 'Krank Keçesi BFI', 'Motorun krank milinde bulunan keçedir. Yağ sızıntısını önler ve motorun verimli çalışmasına yardımcı olur.', 65.78, 19),
(20, 1, 'Krank Keçesi IAT', 'Motorun krank milinde bulunan keçedir. Yağ sızıntısını önler ve motorun verimli çalışmasına yardımcı olur.', 63.24, 20),
(21, 3, 'Fren Hortumu', 'Fren sisteminin önemli bir parçasıdır. Fren hidroliğini tekerleklere ileterek frenleme işleminin düzgün çalışmasını sağlar. Esnek yapısı sayesinde motorun hareketine uyum sağlar.', 57.44, 21),
(22, 3, 'Isıtma Bujisi', 'Dizel motorlarda, motorun soğuk havalarda kolay çalışmasını sağlamak için silindir içini önceden ısıtan parçadır. Sağlıklı ilk çalıştırma ve yakıt verimliliği için gereklidir.', 76.76, 22),
(23, 3, 'Polen Filtresi', 'Araç kabinine giren havayı toz, polen ve zararlı partiküllerden arındıran filtredir. Sürücü ve yolcu konforunu artırır, klima ve havalandırma sisteminin verimli çalışmasını sağlar.', 80.06, 23),
(24, 3, 'Yağ Filtresi', 'Motor yağını süzerek içindeki kir, metal parçacıkları ve tortuları temizler. Motorun daha uzun ömürlü ve verimli çalışmasını sağlar.', 82.83, 24),
(25, 3, 'Yağ Filtresi Grat', 'Motor yağını süzerek içindeki kir, metal parçacıkları ve tortuları temizler. Motorun daha uzun ömürlü ve verimli çalışmasını sağlar.', 87.74, 25),
(26, 3, 'Yağ Filtresi Kruger', 'Motor yağını süzerek içindeki kir, metal parçacıkları ve tortuları temizler. Motorun daha uzun ömürlü ve verimli çalışmasını sağlar.', 89.67, 26),
(27, 3, 'Yağ Filtresi Kruger', 'Motor yağını süzerek içindeki kir, metal parçacıkları ve tortuları temizler. Motorun daha uzun ömürlü ve verimli çalışmasını sağlar.', 93.95, 27),
(28, 3, 'Yağ Filtresi Maher', 'Motor yağını süzerek içindeki kir, metal parçacıkları ve tortuları temizler. Motorun daha uzun ömürlü ve verimli çalışmasını sağlar.', 98.67, 28),
(29, 3, 'Yağ Müşürü Sağ EM', 'Motorun yağ basıncını algılayarak elektronik sisteme bilgi ileten sensördür. Sağ tarafta konumlanır. Yağ basıncı düştüğünde sürücüyü uyararak motorun korunmasına yardımcı olur.', 103.34, 29),
(30, 3, 'Yağ Müşürü ZEG EN', 'ZEG EN uyumlu yağ müşürü, motor yağ basıncını ölçerek elektronik sistemlere bilgi ileten sensördür. Yağ basıncında düşüş olduğunda sürücüyü uyararak motorun zarar görmesini önler.', 104.24, 30);
(31, 4, 'Hararet Musuru frow', 'Motorun sıcaklığını ölçen ve bu bilgiyi aracın göstergesine ya da bilgisayarına ileten sensördür. Motorun aşırı ısınmasını önlemek için sıcaklık takibi yapar.', 114.86, 31),
(32, 4, 'Hava Filtresi kruger', 'Aracın motoruna temiz hava sağlamaya yarayan bir parçadır.', 132.65, 32),
(33, 4, 'Hava Filtresi Voller', 'Aracın motoruna temiz hava sağlamaya yarayan bir parçadır.', 135.15, 33),
(34, 4, 'Polen Filtresi Axam', 'Aracın iç mekanına temiz hava sağlamak için kullanılan bir filtre elemanıdır.', 144.40, 34),
(35, 4, 'Polen Filtresi Fase', 'Aracın iç mekanına temiz hava sağlamak için kullanılan bir filtre elemanıdır.', 148.20, 35),
(36, 4, 'Polen Filtresi Kruger', 'Aracın iç mekanına temiz hava sağlamak için kullanılan bir filtre elemanıdır.', 169.81, 36),
(37, 4, 'Yag Filtresi Filtron', 'Motor yağı içindeki kirleri süzer, motorun temiz çalışmasını sağlar ve motorun ömrünü uzatır.', 171.64, 37),
(38, 4, 'Yag Filtresi Kraft', 'Motor yağı içindeki kirleri süzer, motorun temiz çalışmasını sağlar ve motorun ömrünü uzatır.', 171.93, 38),
(39, 4, 'Yag Filtresi Kruger', 'Motor yağı içindeki kirleri süzer, motorun temiz çalışmasını sağlar ve motorun ömrünü uzatır.', 172.98, 39),
(40, 4, 'Yag Filtresi Sakur', 'Motor yağı içindeki kirleri süzer, motorun temiz çalışmasını sağlar ve motorun ömrünü uzatır.', 173.33, 40);
(41, 5, 'Fren Hortumu Arka Sağ Veya Sol', 'Araçta fren sıvısını ana merkezden tekerleklere ileten, esnek yapısıyla direksiyon ve süspansiyon hareketlerine uyum sağlayan, fren sisteminin güvenli çalışmasını sağlayan önemli bir yedek parçadır.', 52.78, 41),
(42, 5, 'Hava Filtresi Fitpart', 'Fren sıvısını tekerleklere ileten ve fren sisteminin çalışmasını sağlayan esnek bir yedek parçadır.', 52.78, 42),
(43, 5, 'Salincak Burcu On Sag Veya Sol', 'Aracın süspansiyon sisteminde salıncağın şasiye bağlantısını sağlayan, titreşimleri emerek sürüş konforunu artıran kauçuk veya metal destekli yedek parçadır.', 22.81, 43),
(44, 5, 'Supap Lastigi Cdf', 'Motorun emme ve egzoz supaplarında yer alan, motor yağı sızmasını önleyerek yanma odasına yağ geçişini engelleyen küçük ama önemli bir sızdırmazlık elemanıdır.', 37.76, 44),
(45, 5, 'Supap Lastigi Cor', 'Motorun emme ve egzoz supaplarında yer alan, motor yağı sızmasını önleyerek yanma odasına yağ geçişini engelleyen küçük ama önemli bir sızdırmazlık elemanıdır.', 38.71, 45),
(46, 5, 'Supap Lastigi Psa', 'Motorun emme ve egzoz supaplarında yer alan, motor yağı sızmasını önleyerek yanma odasına yağ geçişini engelleyen küçük ama önemli bir sızdırmazlık elemanıdır.', 41.26, 46),
(47, 5, 'Supap Lastigi Reinz', 'Motorun emme ve egzoz supaplarında yer alan, motor yağı sızmasını önleyerek yanma odasına yağ geçişini engelleyen küçük ama önemli bir sızdırmazlık elemanıdır.', 42.53, 47),
(48, 5, 'Supap Lastigi Skt', 'Motorun emme ve egzoz supaplarında yer alan, motor yağı sızmasını önleyerek yanma odasına yağ geçişini engelleyen küçük ama önemli bir sızdırmazlık elemanıdır.', 43.32, 48),
(49, 5, 'Supap Lastigi Skt', 'Motorun emme ve egzoz supaplarında yer alan, motor yağı sızmasını önleyerek yanma odasına yağ geçişini engelleyen küçük ama önemli bir sızdırmazlık elemanıdır.', 44.40, 49),
(50, 5, 'Yag Filtresi', 'Motor yağını süzerek içindeki kir, metal parçacıkları ve tortuları temizleyen, böylece motorun daha uzun ömürlü ve verimli çalışmasını sağlayan bir filtreleme elemanıdır.', 47.46, 50);
(51, 6, 'Polen Filtresi Fitpart', 'Araçların hava dolaşım sistemine yerleştirilen, dışarıdan gelen toz, polen, kir ve zararlı maddelerin içeri girmesini engelleyen bir filtredir.', 79.71, 51),
(52, 6, 'Vantilatör Kayışı Gergi Rulmanı', 'Aracın motorunda bulunan, kayışların düzgün çalışmasını sağlamak için kullanılan bir parçadır.', 83.18, 52),
(53, 6, 'Yağ Filtresi BSG', 'Motor yağını süzerek içindeki kir, metal parçacıkları ve tortuları temizleyen, böylece motorun daha uzun ömürlü ve verimli çalışmasını sağlayan bir filtreleme elemanıdır.', 83.49, 53),
(54, 6, 'Yağ Filtresi Grat', 'Motor yağını süzerek içindeki kir, metal parçacıkları ve tortuları temizleyen, böylece motorun daha uzun ömürlü ve verimli çalışmasını sağlayan bir filtreleme elemanıdır.', 86.37, 54),
(55, 6, 'Yağ Filtresi Kruger Kof15001', 'Motor yağını süzerek içindeki kir, metal parçacıkları ve tortuları temizleyen, böylece motorun daha uzun ömürlü ve verimli çalışmasını sağlayan bir filtreleme elemanıdır.', 87.43, 55),
(56, 6, 'Yağ Filtresi Maher', 'Motor yağını süzerek içindeki kir, metal parçacıkları ve tortuları temizleyen, böylece motorun daha uzun ömürlü ve verimli çalışmasını sağlayan bir filtreleme elemanıdır.', 88.88, 56),
(57, 6, 'Yağ Filtresi Phaff', 'Motor yağını süzerek içindeki kir, metal parçacıkları ve tortuları temizleyen, böylece motorun daha uzun ömürlü ve verimli çalışmasını sağlayan bir filtreleme elemanıdır.', 94.20, 57),
(58, 6, 'Yağ Filtresi Wegna', 'Motor yağını süzerek içindeki kir, metal parçacıkları ve tortuları temizleyen, böylece motorun daha uzun ömürlü ve verimli çalışmasını sağlayan bir filtreleme elemanıdır.', 101.20, 58),
(59, 6, 'Yağ Filtresi Kruger Kof18011', 'Motor yağını süzerek içindeki kir, metal parçacıkları ve tortuları temizleyen, böylece motorun daha uzun ömürlü ve verimli çalışmasını sağlayan bir filtreleme elemanıdır.', 101.22, 59),
(60, 6, 'Yağ Müşürü Maher', 'Aracın motorundaki yağ basıncını ölçen bir sensördür. Bu sensör, motorun yağ pompası tarafından sağlanan yağ basıncını sürekli izler ve motorun doğru çalışabilmesi için yeterli yağ basıncının olup olmadığını denetler.', 104.46, 60);
(61,7, 'hararet musuru facet', ' motorun sıcaklığını ölçen bir sensördür.',90.94,61),
(62,7, 'hararet musuru fae', ' motorun sıcaklığını ölçen bir sensördür.',117.52,62),
(63,7, 'hararet musuru herth', ' motorun sıcaklığını ölçen bir sensördür.',166.42,63),
(64,7, 'hararet musuru triton', ' motorun sıcaklığını ölçen bir sensördür.',168.55,64),
(65,7, 'hararet musuru zegen',' motorun sıcaklığını ölçen bir sensördür.',193.00,65),
(66,7, 'map sensoru gua', 'motorun emme manifoldundaki hava basıncını ölçen bir sensördür.',194.39,66),
(67,7, 'map sensoru zegen', 'motorun emme manifoldundaki hava basıncını ölçen bir sensördür.',248.71,67),
(68,7, 'polen filtresi sion', 'araçların hava dolaşım sistemine yerleştirilen, dışarıdan gelen toz, polen, kir ve zararlı maddelerin içeri girmesini engelleyen bir filtredir.',254.90,68),
(69,7, 'sis farı on sag veya sol ', 'yoğun sis, yağmur, kar veya toz gibi görüş mesafesini azaltan hava koşullarında yolun daha iyi görülmesini sağlamak için kullanılan özel aydınlatma lambalarıdır.',280.23,69),
(70,7, 'yag filtresi', 'motor yağını süzerek içindeki kir, metal parçacıkları ve tortuları temizleyen, böylece motorun daha uzun ömürlü ve verimli çalışmasını sağlayan bir filtreleme elemanıdır.',302.47,70);
(71,8, 'cam su motoru ema', 'araçlardaki ön ve arka camları temizlemek için kullanılan cam yıkama suyunu püskürten küçük bir elektrik motorudur.',117.52,71),
(72,8, 'cam su motoru rockswell', 'araçlardaki ön ve arka camları temizlemek için kullanılan cam yıkama suyunu püskürten küçük bir elektrik motorudur.',132.39,72),
(73,8, 'hararet musuru herth', 'motorun sıcaklığını ölçen bir sensördür.',159.49,73),
(74,8, 'hararet musuru triton', 'motorun sıcaklığını ölçen bir sensördür.',166.13,74),
(75,8, 'krank kecesi on payen', 'motorun en önemli parçalarından biri olan krank milinin sızdırmazlığını sağlayan conta tipi bir parçadır. ',168.55,75),
(76,8, 'krank kecesi on skt', 'motorun en önemli parçalarından biri olan krank milinin sızdırmazlığını sağlayan conta tipi bir parçadır.',171.95,76),
(77,8, 'map sensoru oek', 'motorun emme manifoldundaki hava basıncını ölçen bir sensördür.',183.65,77),
(78,8, 'polen filtresi', 'araçların hava dolaşım sistemine yerleştirilen, dışarıdan gelen toz, polen, kir ve zararlı maddelerin içeri girmesini engelleyen bir filtredir.',190.23,78),
(79,8, 'sis farı on sag veya sol', 'yoğun sis, yağmur, kar veya toz gibi görüş mesafesini azaltan hava koşullarında yolun daha iyi görülmesini sağlamak için kullanılan özel aydınlatma lambalarıdır.',193.00,79),
(80,8, 'yag filtresi','motor yağını süzerek içindeki kir, metal parçacıkları ve tortuları temizleyen, böylece motorun daha uzun ömürlü ve verimli çalışmasını sağlayan bir filtreleme elemanıdır.',194.39,80);
(81,9,'supap lastigi avo','motorun silindir kapağında bulunan supapların gövdesine takılan, yağın yanma odasına sızmasını engelleyen küçük ama kritik bir parçadır.', 18.98,81),
(82,9, 'supap lastigi elring','motorun silindir kapağında bulunan supapların gövdesine takılan, yağın yanma odasına sızmasını engelleyen küçük ama kritik bir parçadır.',19.56,82),
(83,9, 'supap lastigi elwis','motorun silindir kapağında bulunan supapların gövdesine takılan, yağın yanma odasına sızmasını engelleyen küçük ama kritik bir parçadır.',20.56,83),
(84,9, 'supap lastigi glaser','motorun silindir kapağında bulunan supapların gövdesine takılan, yağın yanma odasına sızmasını engelleyen küçük ama kritik bir parçadır.',21.27,84),
(85,9, 'supap lastigi glyco','motorun silindir kapağında bulunan supapların gövdesine takılan, yağın yanma odasına sızmasını engelleyen küçük ama kritik bir parçadır.',21.43,85),
(86,9, 'supap lastigi kraftvoll','motorun silindir kapağında bulunan supapların gövdesine takılan, yağın yanma odasına sızmasını engelleyen küçük ama kritik bir parçadır.',21.75,86),
(87,9, 'supap lastigi payen','motorun silindir kapağında bulunan supapların gövdesine takılan, yağın yanma odasına sızmasını engelleyen küçük ama kritik bir parçadır.',23.73,87),
(88,9, 'supap lastigi rein','motorun silindir kapağında bulunan supapların gövdesine takılan, yağın yanma odasına sızmasını engelleyen küçük ama kritik bir parçadır.',24.81,88),
(89,9, 'supap lastigi skt','motorun silindir kapağında bulunan supapların gövdesine takılan, yağın yanma odasına sızmasını engelleyen küçük ama kritik bir parçadır.',26.10,89),
(90,9, 'supap lastigi topran','motorun silindir kapağında bulunan supapların gövdesine takılan, yağın yanma odasına sızmasını engelleyen küçük ama kritik bir parçadır.',27.92,90);
(91,10,'supap lastigi avortex','motorun silindir kapağında bulunan supapların gövdesine takılan, yağın yanma odasına sızmasını engelleyen küçük ama kritik bir parçadır.',18.89,91),
(92,10,'supap lastigi corteco','motorun silindir kapağında bulunan supapların gövdesine takılan, yağın yanma odasına sızmasını engelleyen küçük ama kritik bir parçadır.',19.33,92),
(93,10,'supap lastigi elring','motorun silindir kapağında bulunan supapların gövdesine takılan, yağın yanma odasına sızmasını engelleyen küçük ama kritik bir parçadır.',19.56,93),
(94,10,'supap lastigi elwis','motorun silindir kapağında bulunan supapların gövdesine takılan, yağın yanma odasına sızmasını engelleyen küçük ama kritik bir parçadır.',20.74,94),
(95,10,'supap lastigi kraftvoll 12010285','motorun silindir kapağında bulunan supapların gövdesine takılan, yağın yanma odasına sızmasını engelleyen küçük ama kritik bir parçadır.',21.27,95),
(96,10,'supap lastigi kraftcoll 12010337','motorun silindir kapağında bulunan supapların gövdesine takılan, yağın yanma odasına sızmasını engelleyen küçük ama kritik bir parçadır.',21.43,96),
(97,10,'supap lastigi payen','motorun silindir kapağında bulunan supapların gövdesine takılan, yağın yanma odasına sızmasını engelleyen küçük ama kritik bir parçadır.',23.59,97),
(98,10,'supap lastigi skt 4s021v','motorun silindir kapağında bulunan supapların gövdesine takılan, yağın yanma odasına sızmasını engelleyen küçük ama kritik bir parçadır.',23.73,98),
(99,10,'supap lastigi skt 4s025v','motorun silindir kapağında bulunan supapların gövdesine takılan, yağın yanma odasına sızmasını engelleyen küçük ama kritik bir parçadır.',24.81,99),
(100,10,'supap lastigi topran','motorun silindir kapağında bulunan supapların gövdesine takılan, yağın yanma odasına sızmasını engelleyen küçük ama kritik bir parçadır.',26.10,100);
(101,11,'Amortisor Tabla Takozu','Amortisör tabla takozu, aracın süspansiyon sisteminde, amortisör ile araç gövdesi arasına yerleştirilen kauçuk veya metal destek parçasıdır.',55.29,101),
(102,11,'Geri Vites Müşürü','Geri vites müşürü (diğer adıyla geri vites lambası müşürü), aracın geri vitese alındığını algılayarak geri vites lambalarının yanmasını sağlayan elektriksel bir anahtardır.',90.94,102),
(103,11,'Supap Lastiği CORTECO','Supap lastiği, içten yanmalı motorlarda supap sapı ile supap kılavuzu arasına yerleştirilen ve motor yağının yanma odasına sızmasını önleyen sızdırmazlık elemanıdır. ',55.40,103),
(104,11,'Supap Lastiği','Supap lastiği, içten yanmalı motorlarda supap sapı ile supap kılavuzu arasına yerleştirilen ve motor yağının yanma odasına sızmasını önleyen sızdırmazlık elemanıdır. ',59.63,104),
(105,11,'Supap Lastiği Elring','Supap lastiği, içten yanmalı motorlarda supap sapı ile supap kılavuzu arasına yerleştirilen ve motor yağının yanma odasına sızmasını önleyen sızdırmazlık elemanıdır. ',62.85,105),
(106,11,'Supap Lastiği Reinz','Supap lastiği, içten yanmalı motorlarda supap sapı ile supap kılavuzu arasına yerleştirilen ve motor yağının yanma odasına sızmasını önleyen sızdırmazlık elemanıdır.',100.48,106),
(107,11,'Supap Lastiği Skt','Supap lastiği, içten yanmalı motorlarda supap sapı ile supap kılavuzu arasına yerleştirilen ve motor yağının yanma odasına sızmasını önleyen sızdırmazlık elemanıdır.',37.76,107),
(108,11,'Yağ Filtresi','Motor yağını süzerek içindeki kir, metal parçacıkları ve tortuları temizleyen filtredir. Temiz yağın motor parçalarını düzgün şekilde yağlamasını sağlar.',44.56,108),
(109,11,'Yağ Filtresi Bsg','Motor yağını süzerek içindeki kir, metal parçacıkları ve tortuları temizleyen filtredir. Temiz yağın motor parçalarını düzgün şekilde yağlamasını sağlar.',85.67,109),
(110,11,'Yağ Filtresi Fase','Motor yağını süzerek içindeki kir, metal parçacıkları ve tortuları temizleyen filtredir. Temiz yağın motor parçalarını düzgün şekilde yağlamasını sağlar.',94.92,110);
(111,12,'Amortisor Tabla Takozu','Amortisör tabla takozu, aracın süspansiyon sisteminde, amortisör ile araç gövdesi arasına yerleştirilen kauçuk veya metal destek parçasıdır.',55.29,111),
(112,12,'Amortisor Tabla Takozu','Amortisör tabla takozu, aracın süspansiyon sisteminde, amortisör ile araç gövdesi arasına yerleştirilen kauçuk veya metal destek parçasıdır.',50.82,112),
(113,12,'Fren Hortumu Arka Sağ','Aracın arka sağ tekerleğine giden hidrolik fren basıncını ileten esnek kauçuk hortumdur. Fren pedalına basıldığında, ana merkezden gelen basıncı arka sağ fren kaliperine veya silindirine ileterek frenin çalışmasını sağlar.',55.56,113),
(114,12,'Fren Hortumu Ön Sağ','Aracın ön sağ tekerleğine hidrolik fren basıncını ileten esnek hortumdur. Fren pedalına basıldığında, ana merkezden gelen basıncı fren kaliperine aktararak tekerleğin yavaşlamasını sağlar.',54.63,114),
(115,12,'Supap Lastiği Corteco','Supap lastiği, içten yanmalı motorlarda supap sapı ile supap kılavuzu arasına yerleştirilen ve motor yağının yanma odasına sızmasını önleyen sızdırmazlık elemanıdır. ',47.85,115),
(116,12,'Supap Lastiği Reinz','Supap lastiği, içten yanmalı motorlarda supap sapı ile supap kılavuzu arasına yerleştirilen ve motor yağının yanma odasına sızmasını önleyen sızdırmazlık elemanıdır.',59.48,116),
(117,12,'Supap Lastiği Cdf','Supap lastiği, içten yanmalı motorlarda supap sapı ile supap kılavuzu arasına yerleştirilen ve motor yağının yanma odasına sızmasını önleyen sızdırmazlık elemanıdır.',37.76,117),
(118,12,'Supap Lastiği Skt','Supap lastiği, içten yanmalı motorlarda supap sapı ile supap kılavuzu arasına yerleştirilen ve motor yağının yanma odasına sızmasını önleyen sızdırmazlık elemanıdır.',44.56,118),
(119,12,'Supap Lastiği','Supap lastiği, içten yanmalı motorlarda supap sapı ile supap kılavuzu arasına yerleştirilen ve motor yağının yanma odasına sızmasını önleyen sızdırmazlık elemanıdır.',22.67,119),
(120,12,'Yağ Filtresi Fase','Motor yağını süzerek içindeki kir, metal parçacıkları ve tortuları temizleyen filtredir. Temiz yağın motor parçalarını düzgün şekilde yağlamasını sağlar.',44.40,120);
(121,13,'Kol Yatak (0.50)','Süspansiyon kolundaki aşınmış (0.50 mm) yatağıdır. Kolun hareketini destekler, sürüş konforu ve yol tutuşunu sağlar.',40.42,121),
(122,13,'Supap Lastiği Corteco','Supap lastiği, içten yanmalı motorlarda supap sapı ile supap kılavuzu arasına yerleştirilen ve motor yağının yanma odasına sızmasını önleyen sızdırmazlık elemanıdır. ',43.32,122),
(123,13,'Radyotör Kapağı Maher','Motorun soğutma sisteminde basıncı ayarlayan kapaktır. Motorun aşırı ısınmasını ve soğutma sıvısının kaynamasını önler. Maher markasına ait kaliteli bir parçadır.',41.26,123),
(124,13,'Fren Hortumu Ön Sağ','Aracın ön sağ tekerleğine hidrolik fren basıncını ileten esnek hortumdur. Fren pedalına basıldığında, ana merkezden gelen basıncı fren kaliperine aktararak tekerleğin yavaşlamasını sağlar.',37.26,114),
(125,13,'Supap Lastiği Corteco','Supap lastiği, içten yanmalı motorlarda supap sapı ile supap kılavuzu arasına yerleştirilen ve motor yağının yanma odasına sızmasını önleyen sızdırmazlık elemanıdır. ',37.85,115),
(126,13,'Supap Lastiği Reinz','Supap lastiği, içten yanmalı motorlarda supap sapı ile supap kılavuzu arasına yerleştirilen ve motor yağının yanma odasına sızmasını önleyen sızdırmazlık elemanıdır.',41.48,116),
(127,13,'Supap Lastiği Cdf','Supap lastiği, içten yanmalı motorlarda supap sapı ile supap kılavuzu arasına yerleştirilen ve motor yağının yanma odasına sızmasını önleyen sızdırmazlık elemanıdır.',43.76,117),
(128,13,'Supap Lastiği Skt','Supap lastiği, içten yanmalı motorlarda supap sapı ile supap kılavuzu arasına yerleştirilen ve motor yağının yanma odasına sızmasını önleyen sızdırmazlık elemanıdır.',41.56,118),
(129,13,'Supap Lastiği','Supap lastiği, içten yanmalı motorlarda supap sapı ile supap kılavuzu arasına yerleştirilen ve motor yağının yanma odasına sızmasını önleyen sızdırmazlık elemanıdır.',47.67,119),
(130,13,'Yağ Filtresi Fase','Motor yağını süzerek içindeki kir, metal parçacıkları ve tortuları temizleyen filtredir. Temiz yağın motor parçalarını düzgün şekilde yağlamasını sağlar.',44.40,120);
(131,14,'Cam Açma Düğmesi','Aracın kapılarındaki elektrikli camların açılıp kapanmasını sağlayan kontrol düğmesidir. Sürücü ve yolcuların camları kolayca hareket ettirmesine olanak tanır.',17.52,131),
(132,14,'Supap Lastiği Corteco','Supap lastiği, içten yanmalı motorlarda supap sapı ile supap kılavuzu arasına yerleştirilen ve motor yağının yanma odasına sızmasını önleyen sızdırmazlık elemanıdır. ',21.32,132),
(133,14,'Supap Lastiği Elwis','Supap lastiği, içten yanmalı motorlarda supap sapı ile supap kılavuzu arasına yerleştirilen ve motor yağının yanma odasına sızmasını önleyen sızdırmazlık elemanıdır.',21.26,133),
(134,14,'Supap LAstiği Elring','Supap lastiği, içten yanmalı motorlarda supap sapı ile supap kılavuzu arasına yerleştirilen ve motor yağının yanma odasına sızmasını önleyen sızdırmazlık elemanıdır.',22.26,134),
(135,14,'Supap Lastiği Corteco','Supap lastiği, içten yanmalı motorlarda supap sapı ile supap kılavuzu arasına yerleştirilen ve motor yağının yanma odasına sızmasını önleyen sızdırmazlık elemanıdır. ',27.85,135),
(136,14,'Supap Lastiği Reinz','Supap lastiği, içten yanmalı motorlarda supap sapı ile supap kılavuzu arasına yerleştirilen ve motor yağının yanma odasına sızmasını önleyen sızdırmazlık elemanıdır.',23.48,136),
(137,14,'Supap Lastiği Cdf','Supap lastiği, içten yanmalı motorlarda supap sapı ile supap kılavuzu arasına yerleştirilen ve motor yağının yanma odasına sızmasını önleyen sızdırmazlık elemanıdır.',23.76,137),
(138,14,'Supap Lastiği Topran','Supap lastiği, içten yanmalı motorlarda supap sapı ile supap kılavuzu arasına yerleştirilen ve motor yağının yanma odasına sızmasını önleyen sızdırmazlık elemanıdır.',24.56,138),
(139,14,'Supap Lastiği Glycor','Supap lastiği, içten yanmalı motorlarda supap sapı ile supap kılavuzu arasına yerleştirilen ve motor yağının yanma odasına sızmasını önleyen sızdırmazlık elemanıdır.',29.67,139),
(140,14,'Supap Lastiği Payen','Supap lastiği, içten yanmalı motorlarda supap sapı ile supap kılavuzu arasına yerleştirilen ve motor yağının yanma odasına sızmasını önleyen sızdırmazlık elemanıdır.',26.40,140);